### ISSUE TITLE
environment.yml error

### ISSUE THREAD

**Issue by neilwang0913** [apple/ml-gmpi#1]
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - cudatoolkit=10.2

**Comment by Xiaoming-Zhao** [comment]
I just tried and it worked on my end. Maybe try to update `conda` based on [this link](https://discuss.pytorch.org/t/cudatoolkit-10-0-not-found-when-installing-pytorch-via-conda/37572).

**Comment by neilwang0913** [comment]
I have updated to conda: conda 4.13.0. But the issue is still there.

**Comment by Xiaoming-Zhao** [comment]
No need. You can choose other combination of PyTorch and CUDA.

**Comment by neilwang0913** [comment]
Any suggestion? I would like to try. Thanks

**Comment by AlexColburnAtApple** [comment]
You can always create an environment and condo install individual components e.g.: 
conda install cudatoolkit=10.2

**Comment by neilwang0913** [comment]
solution: https://anaconda.org/anaconda/cudatoolkit. Thanks.

**Comment by neilwang0913** [comment]
I think the env is for linux not for mac; pyspng is not working as well

**Comment by AlexColburnAtApple** [comment]
Yes, it is a linux environment.  
We ought to note that in the README.

**Comment by Xiaoming-Zhao** [comment]
Does `PIL` work? https://github.com/apple/ml-gmpi/blob/566e9c5aa492cc1bd1f7d9580560d33da3318b9f/gmpi/datasets.py#L107

**Comment by neilwang0913** [comment]
Do you mean pillow:  conda install -c anaconda pillow ? So I should uncomment that and comment the below line. Is there any other part I should make change in the main code?

**Comment by Xiaoming-Zhao** [comment]
Yes, you can `pip install pillow`, uncomment L107 and comment L108.

**Comment by neilwang0913** [comment]
Is there any reason why the pillow is a backup solution? Does that influence the computer performance?

**Comment by Xiaoming-Zhao** [comment]
No. It is just in my development environment, since I directly read from zip file (for FFHQ), sometimes `PIL.Image` says it cannot find some files, a weird issue that I did not dig too much. If `PIL` works for you, then enjoy.
