### ISSUE TITLE
Great Work!!!!!! Few Queries

### ISSUE THREAD

**Issue by VIROBO-15** [apple/ml-gmpi#12]
I have Some conceptual queries regarding the code:

 When I  put the random_pose = False in line 396 of mpi_rendering.py and pass the same pose as given by the dataloader([flat_w2c_mats_real] line 419 train.py ) to self.mpi() function [line 451 mpi_renderer.py] then after 6 iteration on 8 gpu the error arises .

Error:

> pos:  tensor([[0.5797, 0.0647, 0.1850]], device='cuda:0')
> 
> dir:  tensor([[-0.6583, -0.1611,  0.7355]], device='cuda:0')
> 
> u:  tensor([-1.0399, -1.0401, -1.0398, -1.0396], device='cuda:0')
> 
> v:  tensor([-0.6758, -0.6710, -0.6656, -0.6603], device='cuda:0') 
> 
> 
> yaws:  [[-0.6179566383361816]] 
> 
> 
> pitches:  [[0.07507812976837158]] 
> 
> Traceback (most recent call last):
>   File "/proj/cvl/users/x_fahkh/mn/debug-dmpi/gmpi/core/mpi.py", line 106, in homography
>     assert torch.min(u) >= -1, f"Ray's U direction goes out of plane at {distance}, min val {torch.min(u)}"
> AssertionError: Ray's U direction goes out of plane at tensor([[1.1200]], device='cuda:0'), min val -1.0400704145431519

The question is that how is it possible that extrinsic parameter[flat_w2c_mats_real] of real image to leads out of plane of the rays.

**Comment by Xiaoming-Zhao** [comment]
`-1.0400704145431519` is quite close to `-1`, which is the boundary for minimum value. It may be due to precision error on different machines. To resolve this, you can increase the value of `spatial_enlarge_factor` a little bit, e.g., to 1.01 or 1.1:
https://github.com/apple/ml-gmpi/blob/6b538e8a994aa3f3a86de9894e5e69dfe3cd94c3/configs/gmpi.yml#L92

**Comment by VIROBO-15** [comment]
I have made  spatial_enlarge_factor : 1.1 but still I am getting this error

> #Epoch - 0
>   0%|▏                                                                                                                                | 92/69987 [00:42<7:16:10,  2.67it/s]
> pos:  tensor([[-0.6541, -0.0062,  0.2436]], device='cuda:0')
> 
> dir:  tensor([[ 0.5646, -0.1026,  0.8190]], device='cuda:0')
> 
> u:  tensor([-0.1839, -0.1839, -0.1839, -0.1839], device='cuda:0')
> 
> v:  tensor([-0.5088, -0.5048, -0.5008, -0.4968], device='cuda:0') 
> 
> 
> yaws:  [[0.7130070924758911]] 
> 
> 
> pitches:  [[-0.004669070243835449]] 
> 
> <class 'AssertionError'>Traceback (most recent call last):
> 
>   File "/proj/cvl/users/x_fahkh/mn/3D-generation/exps/ddpm-improved-concat-poses-conditioning/models/mpi.py", line 107, in homography
>     assert torch.max(u) <= 1, f"Ray's U direction goes out of plane at {distance}, max val {torch.max(u)}"
> AssertionError: Ray's U direction goes out of plane at tensor([[1.1200]], device='cuda:0'), max val 1.0676274299621582

**Comment by VIROBO-15** [comment]
Is there any way out to use all the images by setting some hyperparamteres?

**Comment by Xiaoming-Zhao** [comment]
If you really want to use all real images, you can:
1. compute the real imges's pose range, i.e., minimum and maximum value of horizontal and vertical angle. Assume they are `pose_min` and `pose_max`;
2. Set the `h_stddev` and `v_stddev` to the largest deviation from the pose's mean. I.e., 
```max(abs(pose_min - pose_mean), abs(pose_max - pose_mean))```
3. Assign those `h_stddev` and `v_stddev` in the `curriculum.py`:
https://github.com/apple/ml-gmpi/blob/6b538e8a994aa3f3a86de9894e5e69dfe3cd94c3/gmpi/curriculums.py#L113-L114
4. Set `cam_pose_n_truncated_stds ` to one or some values slightly larger than one to avoid precision issue, e.g., 1.05:
https://github.com/apple/ml-gmpi/blob/6b538e8a994aa3f3a86de9894e5e69dfe3cd94c3/configs/gmpi.yml#L94

Essentially, you want the truncated Gaussian to cover all real images's poses. Hope this helps.

**Comment by VIROBO-15** [comment]
After Calculating  h_stddev and v_stddev for real image it comes out to be 
```
'h_stddev': 1.5, 
 'v_stddev': 1.0,
```

and also after settinh
```
spatial_enlarge_factor: 1.1
cam_pose_n_truncated_stds: 1.05
```



But I am still get this 

> pos:  tensor([[-0.9283, -0.3449,  0.8610]], device='cuda:0')
> 
> dir:  tensor([[0.9383, 0.2390, 0.2504]], device='cuda:0')
> 
> u:  tensor([0.0191, 0.0190, 0.0189, 0.0189], device='cuda:0')
> 
> v:  tensor([-0.0484, -0.0480, -0.0476, -0.0471], device='cuda:0') 
> 
> 
> yaws:  [[1.4311634302139282]] 
> 
> 
> pitches:  [[-0.05110371112823486]] 
> 
> Traceback (most recent call last):
>   File "/proj/cvl/users/x_fahkh/mn/debug-dmpi/gmpi/core/mpi.py", line 107, in homography
>     assert torch.max(u) <= 1, f"Ray's U direction goes out of plane at {distance}, max val {torch.max(u)}"
> AssertionError: Ray's U direction goes out of plane at tensor([[1.1200]], device='cuda:0'), max val 3.882153272628784

**Comment by Xiaoming-Zhao** [comment]
The problem comes from that the `h_stddev` and `v_stddev` is too large, which may not be suitable for MPI representation.

MPI (as in the name) is a set of planes. It cannot handle extremely wide range of camera poses. If you have horizontal angle of 1.4915, the rays from camera are almost parallel to the MPI plane. This is too extreme for such a representation.

I recommend filtering out real image whose camera poses are too extreme. You may need to tune the `h_stddev` and `v_stddev` a little bit.
