### ISSUE TITLE
Great Work!!!!!

### ISSUE THREAD

**Issue by VIROBO-15** [apple/ml-gmpi#2]
Hi, Can you Please provide the FFHQ data as, I am unable to download the ffhq dataset from the given google drive (https://drive.google.com/drive/folders/1LTBpJ0W_WLjqza3zdayligS8Dh1V1gA6) due to exceed off quota limit. 

It would be great If you can provide the FFHQ processed dataset(FFHQ256X256, FFHQ512X512, FFHQ1024X1024).

Looking forward for your reply

**Comment by Xiaoming-Zhao** [comment]
Thanks a lot for your interests in this work. We may not be able to provide the processed data trying to avoid any potential LICENSE issue.

`exceed off quota limit` is a common issue as GDrive does not support the command line downloading well (I encountered the same thing). You can use the browser to download the data. I know it is a little bit cumbersome but this may be the only way (I also use this tedious way to download the data).

Hope this helps.

**Comment by fangchangma** [comment]
@VIROBO-15 We will check with legal and see if we can release the pre-processed datasets. Please stay tuned.

**Comment by 3dsf** [comment]
@VIROBO-15  

> Hi, Can you Please provide the FFHQ data as, I am unable to download the ffhq dataset from the given google drive (https://drive.google.com/drive/folders/1LTBpJ0W_WLjqza3zdayligS8Dh1V1gA6) due to exceed off quota limit.

In the past for issues like this, I've cloned the drive to my own google drive and then you avoid the data caps.  
_(Also I just downloaded it outside of my google account with no issues)_

**Comment by VIROBO-15** [comment]
@3dsf 
Thank You for helping but I have also made a copy of the drive in my own google drive but It still shows the same issue.

Can you Please help me out in this...

**Comment by cnnlstm** [comment]
> Thanks a lot for your interests in this work. We may not be able to provide the processed data trying to avoid any potential LICENSE issue.
> 
> `exceed off quota limit` is a common issue as GDrive does not support the command line downloading well (I encountered the same thing). You can use the browser to download the data. I know it is a little bit cumbersome but this may be the only way (I also use this tedious way to download the data).
> 
> Hope this helps.

Thanks for your amazing work, I also encounter the same problem when I download the **tf-records**, but I have the **ffhq-image 1024*1024** files (https://drive.google.com/drive/folders/1tZUcXDBeOibC6jcMCtgRRz67pzrAHeHL). So did the tf-recoards data contains the same 1024*1024 faces as  **ffhq-image 1024*1024** ?

**Comment by Xiaoming-Zhao** [comment]
@cnnlstm My gut is that should be fine but I have not tried that. Just two things:
1. The officially-provided 1024*1024 images (the link you shared) use folder name as `69000`. However, if you follow [StyleGAN2-ADA's processing script](https://github.com/NVlabs/stylegan2-ada-pytorch#preparing-datasets) to extract data from the TFRecords, the folder name is `00069`. Our processed pose file use the same folder name as `00069`. You need to slightly modify the `dataset` class:

    a) We directly read image from zipfile, you need to change it to read from disk:
https://github.com/apple/ml-gmpi/blob/566e9c5aa492cc1bd1f7d9580560d33da3318b9f/gmpi/datasets.py#L49
    b) Modify the folder name to point to the right path when you read data:
https://github.com/apple/ml-gmpi/blob/566e9c5aa492cc1bd1f7d9580560d33da3318b9f/gmpi/datasets.py#L62-L63

2. I am not sure the reason but the zipfile of 1024x1024 occupies ~200GB. However, the officially provided 1024x1024 images (the link you shared) only occupies ~90GB. Not sure whether this will affect the performance. However, I think you can definitely train GMPI with the data you already have.

**Comment by fangchangma** [comment]
> @VIROBO-15 We will check with legal and see if we can release the pre-processed datasets. Please stay tuned.

Unfortunately we were informed by Apple's legal team that we could not release these pre-processed datasets because of privacy concerns.

**Comment by cnnlstm** [comment]
> @cnnlstm My gut is that should be fine but I have not tried that. Just two things:
> 
> 1. The officially-provided 1024*1024 images (the link you shared) use folder name as `69000`. However, if you follow [StyleGAN2-ADA's processing script](https://github.com/NVlabs/stylegan2-ada-pytorch#preparing-datasets) to extract data from the TFRecords, the folder name is `00069`. [Our processed pose file](https://drive.google.com/drive/folders/1JDDtGXZP0Z8OwRROO5VNxOjQgwpUSJDj?usp=sharing) use the same folder name as `00069`. You need to slightly modify the `dataset` class:
>    a) We directly read image from zipfile, you need to change it to read from disk:
>    https://github.com/apple/ml-gmpi/blob/566e9c5aa492cc1bd1f7d9580560d33da3318b9f/gmpi/datasets.py#L49
>    
>    b) Modify the folder name to point to the right path when you read data:
>    https://github.com/apple/ml-gmpi/blob/566e9c5aa492cc1bd1f7d9580560d33da3318b9f/gmpi/datasets.py#L62-L63
> 2. The zipfile of 1024x1024 occupies ~200GB. However, the officially provided 1024x1024 images (the link you shared) only occupies ~90GB. I guess it is because of no compression in the zipfile but I am not 100% sure:  see [this line](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/6f160b3d22b8b178ebe533a50d4d5e63aedba21d/dataset_tool.py#L431).
> 
> Overall, I think you can definitely train GMPI with the data you already have.

Thanks for your detailed reply. 

> I convert the **ffhq-image 1024*1024** to **tf_recoard** files, and obtain different resolution files,  just like files in the Nvidia released **tf_recoard** (https://drive.google.com/drive/folders/1M24jfI-Ylb-k2EGhELSnxssWi9wGUokg). 

> Then I download small **tf_recoard** file (``ffhq-r07.tfrecords``) from the link, and uncompress them to images, meanwhile uncompress my own **ffhq-r07.tfrecords**  files to images. 

>  I check the corresponding images and found that they are exactly the same. So I believe the ``ffhq-r10.recoards`` data contains the same 1024 resolution faces as **ffhq-image 1024*1024**.
