### ISSUE TITLE
Maximum range of yaw and pitches

### ISSUE THREAD

**Issue by VIROBO-15** [apple/ml-gmpi#23]
Hi,

Can you please let me know what is the maximum range of yaw and pitches the GMPI can handle

**Comment by Xiaoming-Zhao** [comment]
We have not stress tested this.

But these two may give you a sense: 

https://github.com/apple/ml-gmpi/blob/672294b56f97bd621a87a7a33a39964abb30c0bc/gmpi/curriculums.py#L113-L114

https://github.com/apple/ml-gmpi/blob/672294b56f97bd621a87a7a33a39964abb30c0bc/configs/gmpi.yml#L94

Essentially, during training, we use sample camera poses (or 3x for AFHQCat) within a 2x standard deviation. So GMPI should be able to handle `[-2 * std, 2 * std]` and extrapolate a little bit.
