### ISSUE TITLE
Code for estimating pose for preprocessing (used in "Deep3DFaceRecon" directory)

### ISSUE THREAD

**Issue by mjmjeong** [apple/ml-gmpi#7]
In the [TRAIN_EVAL.md](https://github.com/apple/ml-gmpi/blob/main/docs/TRAIN_EVAL.md), you used the following commands for estimating camera pose:
```
# For FFHQ
cd ${Deep3DFaceRecon_PATH}
python estimate_pose_ffhq.py --name=pretrained --epoch=20 --img_folder=${GMPI_ROOT}/runtime_dataset/dummy --gmpi_img_res ${RES} --gmpi_root ${GMPI_ROOT}

# For MetFace
cd ${Deep3DFaceRecon_PATH}
python estimate_pose_metfaces.py --name=pretrained --epoch=20 --img_folder=${GMPI_ROOT}/runtime_dataset/dummy --gmpi_root ${GMPI_ROOT} 

```
However, I can not find these codes in the [Deep3DFaceRecon_pytorch](https://github.com/sicxu/Deep3DFaceRecon_pytorch/tree/6ba3d22f84bf508f0dde002da8fff277196fef21) repository. 
I guess you newly made these python files. Could you share these files?

**Comment by Xiaoming-Zhao** [comment]
Hi thanks for your interests. In the `TRAIN_EVAL.md`, I mentioned that using my [modified version](https://github.com/Xiaoming-Zhao/Deep3DFaceRecon_pytorch#prepare-prerequisite-models) of the `Deep3DFaceRecon_pytorch`. I only modified some small things, e.g., adding the scripts you mentioned and adding several new command line arguments etc.

Maybe I should make it clearer.
